=== ow-mods/ow-mod-db/mods/mod.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Outer Wilds Mod Database Mod",
  "description": "A single mod entry. The file must be named <uniqueName>.json and live in the mods folder.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "uniqueName",
    "repo"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "description": "Human-readable title for your mod."
    },
    "uniqueName": {
      "type": "string",
      "description": "Your mod's ID, unchangeable and unique within the whole database. IMPORTANT: must match uniqueName from your mod's manifest.json."
    },
    "repo": {
      "type": "string",
      "description": "GitHub repository that contains the mod's source code and releases."
    },
    "required": {
      "type": "boolean",
      "description": "Mods marked as required must be installed before starting the game."
    },
    "utility": {
      "type": "boolean",
      "description": "True if this mod isn't useful by itself, and only serves as a dependency for other mods."
    },
    "thumbnailUrl": {
      "type": "string",
      "description": "Full URL to a thumbnail image that will be used on the website and mod manager. Ideally in a 3:1 ratio (example: 900 by 300 pixels)"
    },
    "authorDisplay": {
      "type": "string",
      "description": "Custom name to show in the author field for this mod. Useful if your mod is in an organization, or made by multiple people. Leave blank to use the repository owner name."
    },
    "parent": {
      "type": "string",
      "description": "If this mod is an addon for another mod, place the parent's uniqueName here. For instance, custom planets made with New Horizons would have xen.NewHorizons in this field."
    },
    "alpha": {
      "type": "boolean",
      "description": "True if this mod is made for Outer Wilds Alpha."
    },
    "tags": {
      "type": "array",
      "description": "List of tags that describe the mod, used for filtering mod lists. If changing this list, make sure to also update the tags in the issue template add-mod.yml",
      "items": {
        "enum": [
          "jam",
          "library",
          "gameplay",
          "tweaks",
          "integration",
          "tool",
          "content",
          "story",
          "audiovisual",
          "localization",
          "requires-dlc",
          "pack"
        ]
      }
    },
    "downloadCountOffset": {
      "type": "number",
      "description": "An amount that will be added to the mod's current download count."
    },
    "firstReleaseDateOverride": {
      "type": "string",
      "description": "A date that will override the current first release date. Format: YYYY-MM-DDThh:mm:ssZ"
    },
    "repoVariations": {
      "type": "array",
      "description": "List of previous GitHub repository names. Used for merging download count history. Do not use if current repo is fork of original repo.",
      "items": {
        "type": "string"
      }
    }
  }
}

=== ow-mods/ow-mod-db/mods/pikpik_carrot,shoe,TextureTurtle.2024FallJam.json
{
  "$schema": "./mod.schema.json",
  "authorDisplay": "pikpik_carrot, shoe, Texture Turtle, Toxic",
  "name": "Iceolation",
  "parent": "xen.NewHorizons",
  "repo": "pikpik-carrot/2024FallJam",
  "tags": [
    "jam",
    "story"
  ],
  "uniqueName": "pikpik_carrot,shoe,TextureTurtle.2024FallJam"
}

=== ow-mods/ow-mod-db/mods/Vambok.HearthianParable.json
{
  "$schema": "./mod.schema.json",
  "name": "The Hearthian Parable",
  "repo": "Vambok/HearthianParable",
  "tags": [
    "jam",
    "story",
    "audiovisual"
  ],
  "thumbnailUrl": "https://raw.githubusercontent.com/Vambok/HearthianParable/refs/heads/main/error.png",
  "uniqueName": "Vambok.HearthianParable"
}

=== ow-mods/ow-mod-db/mods/CrazyHasNoIdeaWhatToDo.CandyWorld.json
{
  "$schema": "./mod.schema.json",
  "name": "Candy World",
  "parent": "xen.NewHorizons",
  "repo": "CrazyHasNoIdeaWhatToDo/CandyWorld-Outer-Wilds-Mod-",
  "tags": [
    "content"
  ],
  "thumbnailUrl": "https://raw.githubusercontent.com/CrazyHasNoIdeaWhatToDo/CandyWorld-Outer-Wilds-Mod-/main/thumbnail.png",
  "uniqueName": "CrazyHasNoIdeaWhatToDo.CandyWorld"
}

=== ow-mods/ow-mod-db/mods/Depthbomb.ProbeRoulette.json
{
  "$schema": "./mod.schema.json",
  "authorDisplay": "depthbomb",
  "name": "Probe Roulette",
  "repo": "depthbomb/OuterWildsProbeRoulette",
  "tags": [
    "gameplay",
    "tweaks"
  ],
  "thumbnailUrl": "https://raw.githubusercontent.com/depthbomb/OuterWildsProbeRoulette/refs/heads/main/art/banner.png",
  "uniqueName": "Depthbomb.ProbeRoulette"
}

=== ow-mods/ow-mod-db/mods/Locochoco.KSPShips.json
{
  "$schema": "./mod.schema.json",
  "authorDisplay": "Locochoco & FunkyShoeMan",
  "name": "Kerbal Space Ventures",
  "parent": "Locochoco.SlateShipyard",
  "repo": "loco-choco/Kerbal-Space-Ventures",
  "repoVariations": [
    "ShoosGun/Kerbal-Space-Ventures"
  ],
  "tags": [
    "gameplay",
    "tool"
  ],
  "uniqueName": "Locochoco.KSPShips"
}

=== ow-mods/ow-mod-db/mods/pikpik_carrot.BandTogether.json
{
  "$schema": "./mod.schema.json",
  "authorDisplay": "pikpik_carrot, Etherpod, Ditzy, TheHipOne",
  "name": "Band Together",
  "parent": "xen.NewHorizons",
  "repo": "Etherpod/Band-Together",
  "tags": [
    "jam",
    "content",
    "story",
    "requires-dlc"
  ],
  "uniqueName": "pikpik_carrot.BandTogether"
}

=== ow-mods/ow-mod-db/mods/xen.NewHorizons.json
{
  "$schema": "./mod.schema.json",
  "authorDisplay": "xen, Bwc9876, JohnCorby, MegaPiggy, and friends",
  "name": "New Horizons",
  "repo": "Outer-Wilds-New-Horizons/new-horizons",
  "repoVariations": [
    "xen-42/outer-wilds-new-horizons"
  ],
  "tags": [
    "tool",
    "content",
    "story"
  ],
  "uniqueName": "xen.NewHorizons"
}

=== ow-mods/ow-mod-db/mods/Hamstry.TheLongerTheyLoad.json
{
  "$schema": "./mod.schema.json",
  "authorDisplay": "Hamstry",
  "name": "The Longer They Load",
  "parent": "AnonymousStrangerOW.TheStrangerTheyAre",
  "repo": "Hamstryk/The-Longer-They-Load",
  "tags": [
    "gameplay",
    "requires-dlc"
  ],
  "thumbnailUrl": "https://raw.githubusercontent.com/Hamstryk/The-Longer-They-Load/refs/heads/main/TSTAButGood/owmm_img.png",
  "uniqueName": "Hamstry.TheLongerTheyLoad"
}
